name: Set Issue to ToDo when Assigned

on:
  issues:
    types: [assigned]

jobs:
  update_project_item:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Info
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          project_data=$(gh api graphql -f query='
            query($org: String!, $projectNumber: Int!) {
              organization(login: $org) {
                projectV2(number: $projectNumber) {
                  id
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org="your-org" -f projectNumber=2)
          projectId=$(echo "$project_data" | jq -r '.data.organization.projectV2.id')
          statusFieldId=$(echo "$project_data" | jq -r '.data.organization.projectV2.fields.nodes[] | select(.name=="Status") | .id')
          toDoOptionId=$(echo "$project_data" | jq -r '.data.organization.projectV2.fields.nodes[] | select(.name=="Status") | .options[] | select(.name=="To Do") | .id')
          echo "projectId=$projectId" >> $GITHUB_ENV
          echo "statusFieldId=$statusFieldId" >> $GITHUB_ENV
          echo "toDoOptionId=$toDoOptionId" >> $GITHUB_ENV

      - name: Update Issue Status
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation($projectId: ID!, $itemId: ID!, $statusFieldId: ID!, $optionId: String!) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $projectId
                itemId: $itemId
                fieldId: $statusFieldId
                value: $optionId
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f projectId="$projectId" -f itemId="${{ github.event.issue.node_id }}" -f statusFieldId="$statusFieldId" -f optionId="$toDoOptionId"
