name: Set Issue to ToDo when Assigned

on:
  issues:
    types: [assigned]

jobs:
  update_project_item:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Info
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          project_data=$(gh api graphql -f query='
            query($projectNumber: Int!) {
              viewer {
                projectV2(number: $projectNumber) {
                  id
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
          ' -F projectNumber=2)

          echo "PROJECT_ID=$(echo "$project_data" | jq -r '.data.viewer.projectV2.id')" >> $GITHUB_ENV
          echo "STATUS_FIELD_ID=$(echo "$project_data" | jq -r '.data.viewer.projectV2.fields.nodes[] | select(.name == "Status") | .id')" >> $GITHUB_ENV
          echo "TODO_OPTION_ID=$(echo "$project_data" | jq -r '.data.viewer.projectV2.fields.nodes[] | select(.name == "Status") | .options[] | select(.name == "To Do") | .id')" >> $GITHUB_ENV

      - name: Update Issue Status
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation($project: ID!, $item: ID!, $field: ID!, $option: ID!) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $field
                value: {
                  singleSelectOptionId: $option
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }
          ' -f project=${{ env.PROJECT_ID }} -f item=${{ github.event.issue.node_id }} -f field=${{ env.STATUS_FIELD_ID }} -f option=${{ env.TODO_OPTION_ID }} --silent
